name: Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Get next version
        id: next_version
        run: |
          # COMMIT=$(git rev-list --tags --max-count=1)
          # echo $COMMIT
          # VERSION=$(git describe --tags $COMMIT)
          # echo $VERSION
          VERSION=$(git tag  | grep -E '^v[0-9]' | sort -V | tail -1)
          echo $VERSION
          echo "::set-output name=VERSION::$VERSION"
          # NEXTVERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
          # echo $NEXTVERSION
          # echo "::set-output name=NEXTVERSION::$NEXTVERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next_version.outputs.VERSION }}
          release_name: ${{ steps.next_version.outputs.VERSION }}
          draft: false
          prerelease: false